@extends("layout")

@section('content')
	<h1 id="page-title">My bio</h1>
	<img id="me-img" src="/img/me.jpg">
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum repellendus quam nisi sed expedita incidunt ullam minus nihil dolorem amet.</p>
	<p>Eaque veritatis error magnam, temporibus odio aspernatur blanditiis nesciunt nulla non et, vitae cum? Iure, expedita, aut. Eos, consectetur, voluptatem.</p>
	<p>ситуации, как часть более широкого явления. <span class="highlighter">Автор аргументирует</span> и выстраивает свою позицию через систему фактов.
	В статье выражается развернутая обстоятельная аргументированная концепция автора или редакции по поводу актуальной социологической проблемы. <span class="highlighter">Автор аргументирует</span> Также, в статье журналист обязательно должен интерпретировать факты (это могут быть цифры, дополнительная информация, которая будет правильно расставлять акценты и ярко раскрывать суть вопроса).
	Отличительным аспектом статьи является ее готовность. Если подготавливаемый материал так и не был опубликован <span class="highlighter">Автор аргументирует</span> (не вышел в тираж, не получил распространения), то такой труд относить к статье некорректно. Скорее всего данную работу можно назвать черновиком или заготовкой. Поэтому цель любой статьи является распространение содержащейся в последней информации.</p>
	<p>Lorem ipsum dolor sit amet, consectetur <span class="highlighter">Автор аргументирует</span> adipisicing elit. Sapiente fuga ab culpa impedit, animi iusto dolor odit id cupiditate a amet illo vero. Similique voluptates dolor voluptas, molestias animi repellat non fugiat omnis ipsam iusto nemo tempore dignissimos culpa quod at deserunt, obcaecati nostrum repellendus tempora laborum dolorum? Aliquid optio labore in voluptas, sit fugit possimus accusantium assumenda vel odit. Illum deserunt nisi sequi eos fugiat. Voluptatibus pariatur obcaecati dicta aut, earum neque officia, natus vel reiciendis. Odio hic ullam ad magnam eos deleniti dicta alias, cumque vitae, voluptate distinctio deserunt illum corporis consequuntur earum fuga debitis nesciunt ab voluptatibus, beatae mollitia ratione neque quisquam! Voluptatum quas, ea repudiandae aperiam commodi alias, dolores doloribus distinctio minima autem saepe dolorum possimus in, illo officiis soluta. Earum cumque fugit, ad quo obcaecati. Error saepe laborum, rem mollitia est illo iusto asperiores, sit debitis ipsam ullam, distinctio quos provident commodi veritatis obcaecati quibusdam impedit id, optio alias facilis assumenda eum. Recusandae error, soluta. Consectetur consequatur, iusto voluptatem aperiam, ducimus itaque laboriosam optio tenetur odit iste mollitia unde nemo natus, quas error aut omnis reprehenderit quia aspernatur corporis minus quasi, aliquam praesentium minima. Doloribus repellat suscipit error nemo magni fugit culpa voluptate possimus earum!</p>
@stop